name: Broken Link Checker

on: [push]
#   schedule:
#     - cron: "*/5 * * * *"

jobs:
  broken-link-checker:
    runs-on: ubuntu-latest
    steps:
      - name: blc
        run: npx -p broken-link-checker blc -go http://adrianjost.dev/projects
