name: Broken Link Checker

on:
  schedules:
    - cron: "*/10 * * * *"

jobs:
  broken-link-checker:
    runs-on: ubuntu-latest
    steps:
      - name: check project links
        run: npx -p broken-link-checker blc -gor http://adrianjost.dev
